config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  get '/about_us' => 'home#about_us', as: :about_us
  get '/contact_us' => 'home#contact_us', as: :contact_us
  get '/our_services' => 'home#our_services', as: :our_services
  get '/our_shop' => 'home#our_shop', as: :our_shop

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end 

  def about_us
  end

  def our_services
  end

  def our_shop
  end

  def contact_us
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/home/about_us.html.erb
<div class="row">
  <div class="col-md-6 image_container"> 
    <%= image_tag("porsche.JPG", :alt => "car image") %>
  </div>

  <div class="col-md-6 text_container">
    <h2> About Us </h2><br>
  
  <p> Unstyled Remove the default list-style and left margin on list items (immediate children only). This only applies to immediate children list items, meaning you will need to add the class for any nested lists as well.</p>
  </div>

</div>

app/views/home/contact_us.html.erb
<div class="row">
  <div class="col-md-6 image_container"> 
    <%= image_tag("porsche.JPG", :alt => "car image") %>
  </div><br><br>


  <div class="col-md-6 text_contact_us">
    <div id="address">
    <br>
      <h2> Contact Us </h2><br>

    <h5>Adress:</h5>
      <p>15 Jutland Road Toronto Ontario M8Z 2G6</p>

    <h5><i class="glyphicon glyphicon-envelope"></i> Email: </h5>
      <p> <a href="mailto:summitautocentre@yahoo.ca?subject=AutoQuestion">summitautocentre@yahoo.ca</a></p>

    <h5><span class="glyphicon glyphicon-earphone"></span> Phone: </h5>
      <strong><p class="phone"> 416.252.7277 </p></strong><br>
    </div>  

  <table class="tabletable-striped">

  <tr>
      <th>First name</th>
      <th>Last name</th> 
      <th>Phone</th>
    </tr>
    <tr>
      <td>Toni</td>
      <td>Troka</td> 
      <td>416.716.9394</td>
    </tr>
    <tr>
      <td>George</td>
      <td>Troka</td> 
      <td>416.716.9394</td>
    </tr>
  </table>
  </div><br><br>

   <div class="col-md-12 map"> 
    <%= image_tag("map.png", :alt => "map image") %>
  </div>
  
  </div><br>

app/views/home/index.html.erb
<div id="carousel-example-generic" class="carousel slide hidden-xs" data-ride="carousel" data-interval="3500">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
 
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="/assets/porsche.JPG" alt="image_one">
    <div class="carousel-caption">
          <h3>Our Shop</h3>
      </div>
    </div>
    <div class="item">
      <img src="/assets/bentley.JPG" alt="image_two">
      <div class="carousel-caption">
          <h3>Our Team</h3>
      </div>
    </div>
    <div class="item">
      <img src="/assets/car_one.JPG" alt="image_three">
      <div class="carousel-caption">
          <h3>Our Equipment</h3>
      </div>
    </div>
  </div>
 
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
<!-- Carousel -->
<blockquote class="blockquote-reverse">
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
  <footer>Someone famous in <cite title="Source Title">Source Title</cite></footer>
</blockquote>

app/views/home/our_services.html.erb
<div class="row">
  
  <div class="col-md-6 image_container"> 
    <%= image_tag("porsche.JPG", :alt => "car image") %>
  </div>

  <div class="col-md-6 text_our_services">
    <h2> Our Services </h2><br>
      <dl class="dl-horizontal">
        <dt> Paint</dt>
        <dd> We have new paint room where.... </dd><br>

        <dt> Body</dt>
        <dd> We have new paint room where.... </dd><br>
      
        <dt> Prep room</dt>
        <dd> We have new paint room where.... </dd><br>
      </dl>
  
  </div>
</div>

app/views/home/our_shop.html.erb
<div class="row">
  
  <div class="col-md-6 image_container"> 
    <%= image_tag("porsche.JPG", :alt => "car image") %>
  </div>

  <div class="col-md-6 text_our_shop">
    <h2> Our Shop </h2><br>
        <p> We provide the best quality out there </p>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Summit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Inconsolata:400,700' rel='stylesheet' type='text/css'>
<!-- CSS font-family: 'Inconsolata', ; -->
<link href='http://fonts.googleapis.com/css?family=Gentium+Book+Basic' rel='stylesheet' type='text/css'>
<!-- CSS font-family: 'Gentium Book Basic', serif; -->
</head>

<body data-controller="<%= controller_name %>" data-action="<%= action_name %>">
<div class="page-wrap">
<div class="logo">
  <div class="img-container">
    <%= image_tag("stocklarge.png", size: "400x100")%>
  </div>

  <div class="title">
    <h3>SUMMIT AUTO CENTRE</h3>
  </div>

 <nav class="navbar-fluid navbar-inverse">
 <div class="bar">
    <%= link_to 'HOME', root_path %>
    <%= link_to 'ABOUT US', about_us_path %>
    <%= link_to 'OUR SERVICES', our_services_path %>
    <%= link_to 'OUR SHOP', our_shop_path %>
    <%= link_to 'CONTACT US', contact_us_path %> 
    <a href="mailto:summitautocentre@yahoo.ca?subject=AutoQuestion"><i class='glyphicon glyphicon-envelope'></i></a>
  </div>
</nav>

<%= yield %>
  </div>
</div>

<footer class="container-fluid site-footer">
   
    <div class="address">
      <p><center><h3> 15 JUTLAND ROAD · TORONTO · ONTARIO · M8Z 2G6 </h></center></p>
    </div>

    <div class="container">
        <p class="text-center">&copy 2015 Summit Auto Centre</p>
    </div>
  </div>
  </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
</body>
</html>